### ISSUE TITLE
Fix react-schema exact-optional initialData build failure

### ISSUE THREAD

**Issue by spralle** [surikaterna/formbar#44]
## Context

Discovered while auditing #41 / PR #42. The workspace TypeScript build exposes a separate `@formbar/react-schema` failure under `exactOptionalPropertyTypes`.

## Reproduction

From a clean checkout with dependencies installed:

```sh
bun install --frozen-lockfile
bun run --filter '*' build
```

Observed in `packages/react-schema/src/use-schema-form.ts` around line 80:

```text
error TS2379: Argument ... is not assignable ... with 'exactOptionalPropertyTypes: true'
```

`useSchemaForm` always includes `initialData: mergedInitialData` when calling `useForm`, even when `mergedInitialData` is `undefined`. With exact optional property types, an omitted optional property is distinct from a present property whose value is `undefined`.

The same workspace command can also fail independently in `@formbar/core`; that pre-existing failure is tracked by #19.

## Scope

- Correct option construction in `@formbar/react-schema` so `initialData` is omitted when no initial data/defaults exist and is passed when a value exists.
- Preserve current schema-default and caller-provided initial-data merge behavior.
- Add focused, risk-based coverage for the absent and present/merged `initialData` paths.
- Keep #19 out of scope; it is a parallel, independent build prerequisite.
- Do not broaden this issue into the Scheman/Zod compatibility work in #41 or enum-option work in #34 / PR #40.

## No suppressions

The fix must not use `@ts-ignore`, `@ts-expect-error`, unsafe casts solely to silence TS2379, or disable/relax `exactOptionalPropertyTypes`. Model the optional property correctly at the call site.

## Acceptance criteria

- [ ] When schema defaults and caller `initialData` are both absent, the `useForm` options object omits `initialData` rather than passing `undefined`.
- [ ] When defaults and/or caller `initialData` exist, the current precedence and merged value are preserved.
- [ ] `bun run --filter @formbar/react-schema build` passes.
- [ ] `bun run --filter '*' build` no longer reports TS2379 from `packages/react-schema/src/use-schema-form.ts`; #19 may still fail independently until resolved.
- [ ] Focused tests cover the absent-property path and the supplied/merged-data path, proportional to the runtime and type-construction risk.
- [ ] Relevant lint/tests/build checks pass with no suppressions or compiler-option weakening.
- [ ] If publishable `@formbar/react-schema` source changes, add a **patch** changeset for `@formbar/react-schema` because this is a backward-compatible build/type fix. If resolution proves test/config-only, document why no changeset is required.

## Dependencies

- **Blocks:** #41.
- Consequently blocks #34 and PR #40, which depend on #41.
- **Parallel independent prerequisite:** #19 must also be resolved before the full workspace build can be green; neither issue should absorb or be treated as fixing the other.

## Release/operator impact

No intended API or runtime behavior change. The publishable package should regain compatibility with the repository's strict TypeScript build while retaining existing initial-data semantics.

**Comment by spralle** [comment]
Status: implemented

Implemented in commit `acf2011` and opened PR #46.

Evidence:
- focused initial-data tests: 3 passed
- root tests: 652 passed
- lint: passed
- root distribution build: passed
- `@formbar/react-schema` TypeScript build: passed
- full workspace TypeScript build: `@formbar/react-schema` passed; remaining failures are independent #19 and the `@formbar/from-schema` compatibility work in #41
- diff check: passed

Ready for Auditor verification. No approved code-principle exceptions.

**Comment by spralle** [comment]
Status: **in_review**

Auditor handoff: **verified** for PR #46 at exact head acf20117769154eaa0bf98bd489848783c1d92cd.

- Auditor evidence: two serial full-suite passes completed successfully; focused initial-data coverage passed (3 tests), root suite passed (652 tests), lint passed, root distribution build passed, and @formbar/react-schema TypeScript build passed.
- CI: ci PASS (29s): https://github.com/surikaterna/formbar/actions/runs/34025820334/job/101466476230
- Merge readiness: CLEAN / MERGEABLE.
- Review state: 0 unresolved review threads, 0 pending review requests, no change-request review, and Copilot review recommended approval with 0 findings.
- Acceptance/code principles: optional initialData is omitted when absent, merge precedence is retained, focused risk-based tests and a patch changeset are present, and no suppressions or approved exceptions were recorded.
- Release impact: patch-level @formbar/react-schema strict-TypeScript compatibility fix; no intended API or runtime behavior change.

Dependency note: #19 is merged. After #46 merges, #41 / PR #42 can integrate updated main containing both #19 and #44. PR #42 and PR #40 were not touched.

Next gate: merge PR #46 using the repository-standard merge commit without bypass, then close #44.

**Comment by spralle** [comment]
Status: **closed**

PR #46 merged to main with the repository-standard merge commit, without bypass.

- Verified head: acf20117769154eaa0bf98bd489848783c1d92cd
- Merge SHA: 9946e3f3c8ea959275177df136a6c4afd12ffe21
- Merge URL: https://github.com/surikaterna/formbar/commit/9946e3f3c8ea959275177df136a6c4afd12ffe21
- PR CI before merge: PASS
- Post-merge main checks: CI PASS, Publish PASS, Deploy to GitHub Pages PASS. Pages reported non-blocking Node.js 20 action-deprecation warnings.
- Release note: patch changeset included for @formbar/react-schema; no intended API or runtime behavior change.

Fixes #44 closed this issue automatically. Main now contains both #19 and #44.
